name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: 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
          owner: FongMi
          base: cfsxy/CatVodSpider01
          head: FongMi/CatVodSpider

