name: Sync Fork

on:
   - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: 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
          owner: FongMi
          base: cfsxy/CatVodSpider01
          head: FongMi/CatVodSpider

